// role-permissions.ts
import { PERMISSIONS, Permission } from "./permission";

export const ROLE_PERMISSIONS: Record<string, Permission[]> = {
  PARTNER: Object.values(PERMISSIONS),

  // CA Manager
  MANAGER: [
    // CLIENT
    PERMISSIONS.CLIENT_VIEW,
    PERMISSIONS.CLIENT_CREATE,
    PERMISSIONS.CLIENT_EDIT,
    PERMISSIONS.CLIENT_DEACTIVATE,

    // COMPLIANCE
    PERMISSIONS.COMPLIANCE_VIEW,
    PERMISSIONS.COMPLIANCE_CREATE,
    PERMISSIONS.COMPLIANCE_EDIT,
    PERMISSIONS.COMPLIANCE_COMPLETE,

    // DOCUMENTS
    PERMISSIONS.DOCUMENT_VIEW,
    PERMISSIONS.DOCUMENT_UPLOAD,
    PERMISSIONS.DOCUMENT_DOWNLOAD,
    PERMISSIONS.DOCUMENT_REQUEST,

    // REMINDERS
    PERMISSIONS.REMINDER_TRIGGER,
    PERMISSIONS.REMINDER_PAUSE,
    PERMISSIONS.REMINDER_RESUME,

    // TEAM (read-only)
    PERMISSIONS.TEAM_VIEW,
  ],

  // Junior
  JUNIOR: [
    PERMISSIONS.CLIENT_VIEW,
    PERMISSIONS.COMPLIANCE_VIEW,
    PERMISSIONS.DOCUMENT_VIEW,
    PERMISSIONS.DOCUMENT_UPLOAD,
    PERMISSIONS.DOCUMENT_DOWNLOAD,
  ],
};
